### ISSUE TITLE
empty output file generated using mircat2

### ISSUE THREAD

**Issue by Toral-Manvar** [sRNAworkbenchuea/UEA_sRNA_Workbench#15]
Hello,

I am using commandline to run mircat2 using following command:

`java -jar ./release/Workbench.jar -tool mircat2 -config mircat2.json`

**I don't have reference genome for my plant sRNA sample, so I am using transcriptome assembly as genome reference.**

Following is the configuration json file file I am using:
```

{
    "srna_files": [
        {
            "srna_filename": "test.fq"
        }
    ],
    "genome_filename": "Trinity_unigene.fasta",
    "miRCAT2_Output_Dir" : "mircat2_analysis",
    "miRCAT2_params" : "mircat2_parameters.cfg",
    "annotation_filename" : ""
}

```

**But getting empty output file. Following is the log for the same**

> Added sRNA file: test.fq
> Added genome file: Trinity_unigene.fasta
> Param extend is not a valid parameter
> Filtered out 0 poor complexity sequences
> Formatting fasta files 0h0m3s304.504ms
> Creating sequence table 0h0m0s052.122ms
> 
> Writing combined fasta 0h0m0s023.335ms
> Building unique sequence table 0h0m0s135.915ms
> Patman: preprocessing file 0h0m0s240.713ms
> Patman: Optional unix conversions 0h0m0s019.302ms
> Patman: mapping fasta files 0h0m2s058.706ms
> Patman: Postprocessing 0h0m0s015.041ms
> Sorting file 0h0m0s591.299ms
> Filtering alignments 0h0m0s007.002ms
> importing alignments to DB 0h0m0s062.524ms
> Oct 01, 2021 3:20:06 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
> WARNING: WORKBENCH: Reference set none already in database. Attaching to the already persisted reference
> Oct 01, 2021 3:20:06 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
> WARNING: WORKBENCH: Reference set genome already in database. Attaching to the already persisted reference
> -- Stopwatch time(s) for 'Consensus annotation by CSVREAD' --
> Total elapsed time: 0h0m0s052.802ms
> Lap 1: 0h0m0s002.413ms    aligned query
> Lap 2: 0h0m0s000.022ms    writing aligned
> Lap 3: 0h0m0s001.240ms    unmapped query
> Lap 4: 0h0m0s000.012ms    writing mapped
> Lap 5: 0h0m0s049.094ms    CSVREAD of Unique sequences
> Last lap time to stop : 0h0m0s000.020ms
> Lap times : max/min/avg = 0h0m0s049.094ms / 0h0m0s000.012ms / 0h0m0s010.556ms
> -- End of stopwatch time(s) --
> Adding intergenic value to unique sequences for mappings 0h0m0s090.735ms
> Calculating alignment totals 0h0m0s005.742ms
> Oct 01, 2021 3:20:06 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
> WARNING: WORKBENCH: No aligned sequences were found for GFF annotation.
> Annotating all sequences 0h0m0s482.385ms
> done Database
> Something has finished... : Database
> -- Stopwatch time(s) --
> StopWatch still running (call stop() to stop).
> Lap 1: 0h0m3s304.504ms    Formatting fasta files
> Lap 2: 0h0m0s052.122ms    Creating sequence table
> Lap 3: 0h0m0s023.335ms    Writing combined fasta
> Lap 4: 0h0m0s135.915ms    Building unique sequence table
> Lap 5: 0h0m0s240.713ms    Patman: preprocessing file
> Lap 6: 0h0m0s019.302ms    Patman: Optional unix conversions
> Lap 7: 0h0m2s058.706ms    Patman: mapping fasta files
> Lap 8: 0h0m0s015.041ms    Patman: Postprocessing
> Lap 9: 0h0m0s591.299ms    Sorting file
> Lap 10: 0h0m0s007.002ms   Filtering alignments
> Lap 11: 0h0m0s062.524ms   importing alignments to DB
> Lap 12: 0h0m0s090.735ms   Adding intergenic value to unique sequences for mappings
> Lap 13: 0h0m0s005.742ms   Calculating alignment totals
> Lap 14: 0h0m0s482.385ms   Annotating all sequences
> Lap times : max/min/avg = 0h0m3s304.504ms / 0h0m0s005.742ms / 0h0m0s506.380ms
> -- End of stopwatch time(s) --
> checking: Database connections
> node: miRCat2 is active: false
> Oct 01, 2021 3:20:07 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
> SEVERE: WORKBENCH: miRCat has not been configured. Please set the genome and output path and check the parameters
> Wating for user config 0h0m0s007.097ms
> Reading genome file 0h0m10s266.684ms
> java.lang.NullPointerException
> 	at uk.ac.uea.cmp.srnaworkbench.tools.mircat2.WF.MiRCat2Module.process(MiRCat2Module.java:196)
> 	at uk.ac.uea.cmp.srnaworkbench.workflow.WorkflowModule.run(WorkflowModule.java:128)
> 	at java.lang.Thread.run(Thread.java:748)
> Oct 01, 2021 3:20:17 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
**> SEVERE: WORKBENCH: miRCat2: Message: null;**
> Stack Trace: uk.ac.uea.cmp.srnaworkbench.tools.mircat2.WF.MiRCat2Module.process(MiRCat2Module.java:196)
> uk.ac.uea.cmp.srnaworkbench.workflow.WorkflowModule.run(WorkflowModule.java:128)
> java.lang.Thread.run(Thread.java:748)
>  
> Something has finished... : miRCat2
> -- Stopwatch time(s) --
> StopWatch still running (call stop() to stop).
> Lap 1: 0h0m3s304.504ms    Formatting fasta files
> Lap 2: 0h0m0s052.122ms    Creating sequence table
> Lap 3: 0h0m0s023.335ms    Writing combined fasta
> Lap 4: 0h0m0s135.915ms    Building unique sequence table
> Lap 5: 0h0m0s240.713ms    Patman: preprocessing file
> Lap 6: 0h0m0s019.302ms    Patman: Optional unix conversions
> Lap 7: 0h0m2s058.706ms    Patman: mapping fasta files
> Lap 8: 0h0m0s015.041ms    Patman: Postprocessing
> Lap 9: 0h0m0s591.299ms    Sorting file
> Lap 10: 0h0m0s007.002ms   Filtering alignments
> Lap 11: 0h0m0s062.524ms   importing alignments to DB
> Lap 12: 0h0m0s090.735ms   Adding intergenic value to unique sequences for mappings
> Lap 13: 0h0m0s005.742ms   Calculating alignment totals
> Lap 14: 0h0m0s482.385ms   Annotating all sequences
> Lap times : max/min/avg = 0h0m3s304.504ms / 0h0m0s005.742ms / 0h0m0s506.380ms
> -- End of stopwatch time(s) --
> checking: miRCat2 connections
> Workflow complete
> Finish

I even tried using GUI, but got no success.
It seems, alignment is not able to happen.
I will really appreciate any help in resolving this error.

Thank you.

**Comment by Toral-Manvar** [comment]
For any one who is willing  to use sRNAWorkbench for sRNA analysis, all the errors are mostly related to input file format or output folder.
mircat2 doesn't accept direct fastq file as input instead it take non-redundant/collapse file which can be generated from its filter tool. Also you need to prepare empty output folder and give it in config json file as mircat2 doesn't generated it by its own and throw error otherwise. So basically you have to give genome fasta, sRNA fasta, parameter file and empty output folder name in config json file and it will run properly.
