### ISSUE TITLE
The workbench.jar not opening

### ISSUE THREAD

**Issue by sajjadiqbal13** [sRNAworkbenchuea/UEA_sRNA_Workbench#29]
I have used java -jar Workbench.jar.
But it showing error could load or find the class MainAppFX.

**Comment by williamshell** [comment]
Hi, @sajjadiqbal13 @sRNAworkbenchuea 
I am facing the same problem under Ubuntu. I believe this issue stems from a Java error which is relatived with javafx. I suggest adding "--module-path $javafx --add-modules javafx.controls" in your command line. 

Althouth I have used the following command, this error was reported.

```
/usr/lib/jvm/java-11-openjdk-amd64/bin/java --module-path 
 /usr/share/openjfx/lib --add-modules=javafx.swing,javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.web -jar ./ServerWorkbench.jar -tool mircat2 -config default_mircat2.json 
```

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/home/a/data/Workbench_4.5.1/ServerWorkbench.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Added sRNA file: test.txt
Added genome file: IRGSP_1_0_transcript_2023_03_15.fa
Jan 27, 2024 4:19:27 PM uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger log
SEVERE: WORKBENCH: 
java.lang.IllegalStateException: Toolkit not initialized
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:410)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:405)
	at javafx.graphics/javafx.application.Platform.runLater(Platform.java:150)
	at uk.ac.uea.cmp.srnaworkbench.utils.MessageBox.messageJFX(MessageBox.java:18)
	at uk.ac.uea.cmp.srnaworkbench.workflow.PreconfiguredWorkflows.runCommandLineWorkflowMiRCat2(PreconfiguredWorkflows.java:1116)
	at uk.ac.uea.cmp.srnaworkbench.tools.ToolBox$15.startTool(ToolBox.java:747)
	at uk.ac.uea.cmp.srnaworkbench.ServerApp.startWorkbench(ServerApp.java:138)
	at uk.ac.uea.cmp.srnaworkbench.ServerApp.main(ServerApp.java:28)

WORKENCH ERROR: Unrecoverable exception occured: java.lang.IllegalStateException: Toolkit not initialized
```

**Comment by samburger** [comment]
I had the same issue with any version since 4.0.  Installing the previous version 3.2 worked.
